on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Watch and Sync
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            locales/fr.json
            templates/index.json

      - name: Display all modified files (for debugging purpose)
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
          done

      - name: Shopify theme management
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout develop

          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            git checkout main -- $file
          done

          git commit -m "Github Bot - locale fr"
          git push
          